spring:
  application:
    name: money-transfer-system

  datasource:
    url: jdbc:mysql://localhost:3306/money_transfer_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # **Mandatory**
    # set SPRING_DATASOURCE_USERNAME=<username>
    # set SPRING_DATASOURCE_PASSWORD=<password>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /

# Configure log levels
logging:
  level:
    com.banking.moneytransfer: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Enable CORS for angular frontend (development only)
cors:
  allow-origin: "http://localhost:4200"

# **Optional**
# set MOCK_OVERWRITE=false to overwrite the database with mock data
mock:
  overwrite: true